### ISSUE TITLE
Simulate cutting trees?

### ISSUE THREAD

**Issue by TrentBartlem** [devilesk/dota-interactive-map#2]
Would it be possible to have a 'cut tree' tool to simulate what vision changes would occur if trees were cut?

**Comment by devilesk** [comment]
This feature already exists. You can click the cursor icon on the left menu to turn trees on and then you can click trees to cut them. 
![image](https://user-images.githubusercontent.com/643936/32440666-32e0fc0e-c2c2-11e7-8a3e-676b12388b44.png)

**Comment by TrentBartlem** [comment]
Thanks! However, cutting trees doesn't seem to affect already-placed wards. Is that intended?

**Comment by devilesk** [comment]
No, that's an oversight. It would definitely make sense to have already placed wards update when trees are cut. Thanks for pointing that out. I'll work on getting it fixed.

**Comment by devilesk** [comment]
Already placed ward vision should now update when trees are cut.
