### ISSUE TITLE
Add Support Of Height Map

### ISSUE THREAD

**Issue by phamtheson01** [devilesk/dota-interactive-map#6]
Your work is really great but some additional features would improve this much
I suggest to add the Dota 2 height map,really useful to me to create terrain for DotA 1
thanks in advanced
![ảnh](https://user-images.githubusercontent.com/45394243/68097747-5c405380-feeb-11e9-8d7d-1c9c781f19c6.png)

**Comment by devilesk** [comment]
This is something I was working on earlier this year but I never released the update. I've added it now as an option in the right menu, `Overlays -> Elevation`. I also added the 7.21 map and I plan to add the 7.22 map today before 7.23 releases.

**Comment by phamtheson01** [comment]
![ảnh](https://user-images.githubusercontent.com/45394243/70620516-14c78880-1c4a-11ea-90db-13dbd759acb7.png)
could u add detailed heightmap like this ?
